import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { error, mapPrismaError, ok } from "@/lib/api/response";
import { parseJson } from "@/lib/api/validation";
import { requireAccess } from "@/lib/rbac/guards";
import { requireLock } from "@/lib/locks/service";
import argon2 from "argon2";

type CrudConfig = { model: "user" | "role" | "organization" | "menuFeature"; view: string; add: string; edit: string; remove: string; create: z.ZodType; update: z.ZodType };
const db = prisma as unknown as Record<string, { findMany: Function; findUnique: Function; create: Function; update: Function; delete: Function }>;

export async function listResource(request: Request, config: CrudConfig) { const guard = await requireAccess(request, config.view); if (guard.response) return guard.response; return ok(await db[config.model].findMany({ orderBy: { createdAt: "desc" } })); }
export async function createResource(request: Request, config: CrudConfig) { const guard = await requireAccess(request, config.add); if (guard.response) return guard.response; const parsed = await parseJson(request, config.create); if ("response" in parsed) return parsed.response; try { const data = { ...(parsed.data as Record<string, unknown>) }; if (config.model === "user" && typeof data.password === "string") { data.passwordHash = await argon2.hash(data.password); delete data.password; } return ok(await db[config.model].create({ data }), { status: 201 }); } catch (caught) { return mapPrismaError(caught); } }
export async function getResource(request: Request, id: string, config: CrudConfig) { const guard = await requireAccess(request, config.view); if (guard.response) return guard.response; const value = await db[config.model].findUnique({ where: { id } }); return value ? ok(value) : error("NOT_FOUND", "Resource not found", 404); }
export async function updateResource(request: Request, id: string, config: CrudConfig) { const guard = await requireAccess(request, config.edit); if (guard.response) return guard.response; if (!(await requireLock(config.model, id, guard.user.id, request.headers.get("X-Record-Lock-Token")))) return error("LOCKED", "Active record lock required", 423); const parsed = await parseJson(request, config.update); if ("response" in parsed) return parsed.response; try { if (config.model === "user" || config.model === "role") { const current = await db[config.model].findUnique({ where: { id } }); if (current?.isSystemProtected || (current?.isSystemRole && current?.code === "SUPER_ADMIN")) return error("FORBIDDEN", "System resource is protected", 403); } return ok(await db[config.model].update({ where: { id }, data: parsed.data })); } catch (caught) { return mapPrismaError(caught); } }
export async function deleteResource(request: Request, id: string, config: CrudConfig) { const guard = await requireAccess(request, config.remove); if (guard.response) return guard.response; if (!(await requireLock(config.model, id, guard.user.id, request.headers.get("X-Record-Lock-Token")))) return error("LOCKED", "Active record lock required", 423); try { if (config.model === "user" || config.model === "role") { const current = await db[config.model].findUnique({ where: { id } }); if (current?.isSystemProtected || (current?.isSystemRole && current?.code === "SUPER_ADMIN")) return error("FORBIDDEN", "System resource is protected", 403); } return ok(await db[config.model].delete({ where: { id } })); } catch (caught) { return mapPrismaError(caught); } }
