"use client";

import { useEffect, useState } from "react";

type Lock = { id: string; resourceType: string; resourceId: string; expiresAt: string; ownerUser?: { username?: string; displayName?: string } };
export function LockedRecordsCrud() {
  const [locks, setLocks] = useState<Lock[]>([]); const [canForce, setCanForce] = useState(false); const [message, setMessage] = useState("Loading records...");
  async function load() { const [lockResponse, accessResponse] = await Promise.all([fetch("/api/v1/locks"), fetch("/api/v1/me/access")]); const lockBody = await lockResponse.json(); const accessBody = await accessResponse.json(); if (!lockResponse.ok) { setMessage(lockBody.error?.message ?? "Unable to load locks"); return; } setLocks(lockBody.data ?? []); setCanForce((accessBody.data?.permissions ?? []).includes("DD0000006")); setMessage(""); }
  useEffect(() => { void load(); }, []);
  async function forceUnlock(id: string) { const response = await fetch(`/api/v1/locks/${id}/force`, { method: "DELETE" }); const body = await response.json(); if (!response.ok) setMessage(body.error?.message ?? "Unable to force unlock"); else await load(); }
  return <section className="space-y-6"><div><p className="eyebrow">Concurrency control</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Locked Records</h1><p className="mt-2 text-[#6b6962]">Active locks prevent concurrent mutations. Force unlock removes only lock state.</p></div>{message && <p className="rounded-lg border-l-4 border-[#f59e0b] bg-[#fff8e8] p-4 text-sm font-medium text-[#8b5c0a]">{message}</p>}<div className="panel overflow-hidden">{locks.length === 0 && !message ? <div className="p-12 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#e7ede4] text-xl text-[#2b9a66]">✓</div><p className="mt-3 font-bold">No active locks</p><p className="mt-1 text-sm text-[#7a7870]">All records are available for editing.</p></div> : locks.length > 0 && <table className="min-w-full text-left text-sm"><thead className="border-b border-[#ebe9e4] bg-[#fbfaf7]"><tr><th className="px-5 py-3 text-[11px] font-bold uppercase tracking-[0.12em] text-[#7a7870]">Resource</th><th className="px-5 py-3 text-[11px] font-bold uppercase tracking-[0.12em] text-[#7a7870]">Owner</th><th className="px-5 py-3 text-[11px] font-bold uppercase tracking-[0.12em] text-[#7a7870]">Expires</th><th className="px-5 py-3 text-[11px] font-bold uppercase tracking-[0.12em] text-[#7a7870]">Actions</th></tr></thead><tbody>{locks.map((lock) => <tr className="border-b last:border-0 hover:bg-[#fbfaf7]" key={lock.id}><td className="px-5 py-4"><span className="font-bold">{lock.resourceType}</span><span className="ml-2 font-mono text-xs text-[#7a7870]">{lock.resourceId}</span></td><td className="px-5 py-4 text-[#4d4b43]">{lock.ownerUser?.displayName ?? lock.ownerUser?.username ?? "-"}</td><td className="px-5 py-4 text-[#6b6962]">{new Date(lock.expiresAt).toLocaleString()}</td><td className="px-5 py-3">{canForce && <button className="rounded-md border border-[#ead0ca] bg-[#fffaf9] px-3 py-2 text-xs font-bold text-[#a53b36]" onClick={() => void forceUnlock(lock.id)}>Force unlock</button>}</td></tr>)}</tbody></table>}</div></section>;
}
