export default function HomePage() {
  return (
    <main className="page-shell min-h-screen overflow-hidden">
      <div className="mx-auto flex min-h-screen max-w-[1440px] flex-col px-5 py-6 sm:px-10 lg:px-16">
        <header className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#5a5a40] font-bold text-white">N</div><span className="font-bold tracking-tight">Northstar Admin</span></div><a className="rounded-lg border border-[#d4d1cb] bg-white px-4 py-2 text-sm font-bold text-[#4d4b43] hover:border-[#5a5a40]" href="/login">Sign in</a></header>
        <section className="relative grid flex-1 items-center gap-12 py-16 lg:grid-cols-[1.05fr_0.95fr] lg:py-24"><div className="relative z-10"><p className="eyebrow">Secure operations workspace</p><h1 className="mt-5 max-w-3xl text-5xl font-bold leading-[1.02] tracking-[-0.06em] text-[#1a1a1a] sm:text-7xl">Calm control for complex work.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#6b6962]">A production-ready admin foundation for teams that need clear access, safe mutations, and an API that stays ready for what comes next.</p><div className="mt-9 flex flex-wrap gap-3"><a className="rounded-lg bg-[#5a5a40] px-5 py-3.5 text-sm font-bold text-white shadow-lg shadow-[#5a5a40]/20 hover:bg-[#3d3d2b]" href="/login">Enter workspace <span className="ml-2">→</span></a><a className="rounded-lg border border-[#d4d1cb] bg-white px-5 py-3.5 text-sm font-bold text-[#4d4b43] hover:border-[#5a5a40]" href="/api/docs">View API contract</a></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 text-xs font-semibold text-[#7a7870]"><span>✓ HttpOnly sessions</span><span>✓ Database-driven RBAC</span><span>✓ Record-safe edits</span></div></div><div className="relative hidden min-h-[430px] lg:block"><div className="absolute inset-8 rotate-3 rounded-2xl bg-[#8c7355] shadow-2xl shadow-[#3d3d2b]/20" /><div className="absolute inset-0 overflow-hidden rounded-2xl bg-[#3d3d2b] p-6 text-white shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-[#73bd8d]" /><span className="text-xs font-semibold text-white/60">Workspace overview</span></div><span className="text-xs text-white/35">LIVE</span></div><div className="mt-8"><p className="text-xs uppercase tracking-[0.18em] text-[#d7c7ae]">System posture</p><p className="mt-2 text-3xl font-bold">Everything in place.</p></div><div className="mt-10 grid grid-cols-2 gap-3">{[["7", "Features"], ["4", "Actions"], ["120", "API / min"], ["120s", "Lock TTL"]].map(([value, label]) => <div className="rounded-xl border border-white/10 bg-white/5 p-4" key={label}><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-white/45">{label}</p></div>)}</div><div className="mt-6 rounded-xl bg-[#5a5a40] p-4"><p className="text-xs font-semibold text-white/60">Protected by design</p><div className="mt-3 h-2 rounded-full bg-white/15"><div className="h-2 w-4/5 rounded-full bg-[#d9c5a4]" /></div></div></div></div></section>
        <footer className="flex flex-col gap-2 border-t border-[#ebe9e4] py-5 text-xs text-[#7a7870] sm:flex-row sm:justify-between"><span>Northstar Admin · Built for intentional operations</span><span>Next.js · PostgreSQL · RBAC</span></footer>
      </div>
    </main>
  );
}
