"use client";
import { useEffect, useRef, useState } from "react";

type LockOwner = { id: string; username: string; displayName: string | null };

export function useRecordLock(resourceType: string, resourceId: string, enabled = true) {
  const [token, setToken] = useState<string | null>(null); const [readOnly, setReadOnly] = useState(false); const [checking, setChecking] = useState(Boolean(enabled)); const [owner, setOwner] = useState<LockOwner | null>(null); const [lockId, setLockId] = useState<string | null>(null); const tokenRef = useRef<string | null>(null); const lockIdRef = useRef<string | null>(null);
  useEffect(() => { tokenRef.current = null; lockIdRef.current = null; setToken(null); setLockId(null); setOwner(null); if (!enabled) { setReadOnly(false); setChecking(false); return; } let active = true; setChecking(true); fetch("/api/v1/locks/acquire", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ resourceType, resourceId }) }).then(async (response) => { const body = await response.json().catch(() => ({})); if (!active) return; const lock = body.data?.lock ?? body.error?.details; if (response.ok && body.data?.token) { tokenRef.current = body.data.token; lockIdRef.current = lock?.id ?? null; setToken(body.data.token); setLockId(lock?.id ?? null); setOwner(lock?.ownerUser ?? null); setReadOnly(false); } else { setOwner(lock?.ownerUser ?? null); setReadOnly(true); } setChecking(false); }).catch(() => { if (active) { setReadOnly(true); setChecking(false); } }); const timer = window.setInterval(() => { if (lockIdRef.current && tokenRef.current) void fetch(`/api/v1/locks/${lockIdRef.current}/heartbeat`, { method: "POST", headers: { "X-Record-Lock-Token": tokenRef.current } }); }, 30000); const release = () => { if (lockIdRef.current && tokenRef.current) void fetch(`/api/v1/locks/${lockIdRef.current}`, { method: "DELETE", headers: { "X-Record-Lock-Token": tokenRef.current }, keepalive: true }); }; window.addEventListener("pagehide", release); return () => { active = false; window.clearInterval(timer); window.removeEventListener("pagehide", release); }; }, [enabled, resourceType, resourceId]);
  return { token, readOnly, checking, owner, lockId };
}
