"use client";
import { signIn } from "next-auth/react";
import { FormEvent, useState } from "react";

export default function LoginPage() {
  const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const result = await signIn("credentials", { username: form.get("username"), password: form.get("password"), redirect: false, callbackUrl: "/dashboard" }); if (result?.error) setError("Invalid username or password"); else window.location.assign("/dashboard"); }
  return <main className="page-shell grid min-h-screen lg:grid-cols-[0.9fr_1.1fr]"><section className="relative hidden overflow-hidden bg-[#3d3d2b] p-10 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-24 top-24 h-80 w-80 rounded-full border-[34px] border-[#8c7355]/30" /><div className="relative flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#8c7355] font-bold">N</div><span className="font-bold">Northstar Admin</span></div><div className="relative max-w-md"><p className="eyebrow text-[#d7c7ae]">Welcome back</p><h1 className="mt-5 text-5xl font-bold leading-tight tracking-[-0.05em]">Make space for better decisions.</h1><p className="mt-5 leading-7 text-white/60">A warm, focused workspace for managing people, access, integrations, and the records that matter.</p></div><p className="relative text-xs text-white/35">Secure operations workspace · v0.1</p></section><section className="flex items-center justify-center p-6 sm:p-10"><form onSubmit={submit} className="w-full max-w-md"><div className="mb-10 lg:hidden"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#5a5a40] font-bold text-white">N</div><span className="font-bold">Northstar Admin</span></div></div><p className="eyebrow">Secure sign in</p><h1 className="mt-3 text-4xl font-bold tracking-tight">Welcome back.</h1><p className="mt-3 text-[#6b6962]">Use your workspace credentials to continue.</p><div className="mt-8 space-y-5"><label className="grid gap-2 text-sm font-bold">Username<input name="username" required className="input-base" placeholder="Enter username" /></label><label className="grid gap-2 text-sm font-bold">Password<input name="password" required type="password" className="input-base" placeholder="Enter password" /></label>{error && <p className="rounded-lg border-l-4 border-[#dc2626] bg-[#fff4f2] p-3 text-sm font-medium text-[#a53b36]">{error}</p>}<button className="w-full rounded-lg bg-[#5a5a40] py-3.5 font-bold text-white shadow-lg shadow-[#5a5a40]/15 hover:bg-[#3d3d2b]">Sign in to workspace <span className="ml-2">→</span></button></div><p className="mt-8 text-center text-xs text-[#9b988e]">Your session is protected with HttpOnly cookies.</p></form></section></main>;
}
