import Link from "next/link";

const cards = [
  ["User directory", "AM0000002", "/dashboard/users", "Manage people and access", "↗"],
  ["Access control", "AM0000003", "/dashboard/roles", "Shape roles and policies", "◇"],
  ["Organizations", "AM0000004", "/dashboard/organizations", "Coordinate your teams", "▦"],
  ["Record safety", "AM0000006", "/dashboard/locked-records", "Monitor active editors", "⊙"]
] as const;

export default function DashboardPage() {
  return <section className="space-y-8">
    <div className="relative overflow-hidden rounded-2xl bg-[#5a5a40] p-7 text-white shadow-[0_12px_30px_rgba(61,61,43,0.18)] sm:p-10">
      <div className="absolute -right-16 -top-24 h-64 w-64 rounded-full border-[24px] border-[#8c7355]/35" /><div className="absolute bottom-[-76px] right-40 h-44 w-44 rounded-full bg-[#8c7355]/30 blur-2xl" />
      <div className="relative max-w-2xl"><p className="eyebrow text-[#e3d5bf]">Sunday, August 09, 2026</p><h1 className="mt-4 text-3xl font-bold tracking-[-0.04em] sm:text-5xl">Make every operation feel intentional.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-white/70 sm:text-base">Your workspace is ready. Review access, keep records safe, and move your team forward from one calm control surface.</p><div className="mt-7 flex flex-wrap gap-3"><Link className="rounded-lg bg-white px-4 py-3 text-sm font-bold text-[#3d3d2b] shadow-lg shadow-black/10 hover:bg-[#f1f0ea]" href="/dashboard/users">Open user directory</Link><Link className="rounded-lg border border-white/25 px-4 py-3 text-sm font-bold text-white hover:bg-white/10" href="/dashboard/features">Manage features</Link></div></div>
    </div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["7", "Workspace features", "Seeded and protected", "bg-[#eee8dc]"], ["4", "Permission actions", "View, add, edit, delete", "bg-[#e7ede4]"], ["120", "API requests / min", "Protected default limit", "bg-[#eee9e1]"], ["120s", "Lock duration", "Heartbeat keeps edits safe", "bg-[#e9e7ed]"]] .map(([value, label, meta, tone]) => <div className={`panel ${tone} p-5`} key={label}><div className="flex items-start justify-between"><p className="text-sm font-semibold text-[#6b6962]">{label}</p><span className="h-2 w-2 rounded-full bg-[#8c7355]" /></div><p className="mt-5 text-3xl font-bold tracking-tight text-[#1a1a1a]">{value}</p><p className="mt-1 text-xs text-[#7a7870]">{meta}</p></div>)}</div>
    <div><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Workspace shortcuts</p><h2 className="mt-1 text-2xl font-bold tracking-tight">Keep work moving</h2></div><span className="hidden text-sm text-[#7a7870] sm:block">Permission-filtered navigation</span></div><div className="grid gap-4 md:grid-cols-2">{cards.map(([label, code, href, description, icon]) => <Link className="panel group flex items-center gap-4 p-5 hover:-translate-y-0.5 hover:border-[#b8b4a7] hover:shadow-[0_8px_24px_rgba(26,26,26,0.08)]" href={href} key={code}><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[#f1f0ea] text-xl text-[#5a5a40] transition group-hover:bg-[#5a5a40] group-hover:text-white">{icon}</span><span className="min-w-0"><span className="block text-base font-bold text-[#1a1a1a]">{label}</span><span className="mt-1 block text-sm text-[#6b6962]">{description}</span></span><span className="ml-auto text-[#9b988e] transition group-hover:translate-x-1 group-hover:text-[#5a5a40]">→</span></Link>)}</div></div>
    <div className="grid gap-4 lg:grid-cols-[1.2fr_0.8fr]"><div className="panel p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">System posture</p><h2 className="mt-1 text-xl font-bold">Everything is in place</h2></div><span className="status-badge status-active">Healthy</span></div><div className="mt-6 space-y-4">{[["Authentication", "HttpOnly sessions and bearer tokens"], ["Permission engine", "Database-derived access on every request"], ["Record locking", "Global protection enabled by default"]].map(([label, value]) => <div className="flex items-center gap-3" key={label}><span className="grid h-7 w-7 place-items-center rounded-full bg-[#e7ede4] text-xs text-[#2b9a66]">✓</span><div><p className="text-sm font-bold">{label}</p><p className="text-xs text-[#7a7870]">{value}</p></div></div>)}</div></div><div className="rounded-xl bg-[#3d3d2b] p-6 text-white"><p className="eyebrow text-[#d7c7ae]">Need a closer look?</p><h2 className="mt-2 text-xl font-bold">Explore your API contract</h2><p className="mt-2 text-sm leading-6 text-white/60">Open the interactive documentation and inspect every protected route.</p><Link className="mt-6 inline-flex rounded-lg bg-[#8c7355] px-4 py-3 text-sm font-bold hover:bg-[#a08870]" href="/api/docs">Open Swagger UI <span className="ml-2">↗</span></Link></div></div>
  </section>;
}
